package com.spotifyxp.dialogs;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.spotifyxp.panels.ContentPanel;

import javax.swing.*;
import java.awt.*;

public class CancelDialog extends JDialog {
    public JPanel contentPane;
    public JButton cancelButton;

    public CancelDialog() {
        setPreferredSize(new Dimension(300, 100));
        setLocation(ContentPanel.frame.getCenter());
        setResizable(false);
        setContentPane(contentPane);
        setModal(true);
    }

    public void showIt() {
        cancelButton.setText("Cancel Login"); //ToDo: Translate
        setTitle("Cancel login?"); //ToDo: Translate
        pack();
        setVisible(true);
        cancelButton.addActionListener(e -> System.exit(0));
    }

    public void closeIt() {
        dispose();
    }

    public static void main(String[] args) {
        new CancelDialog().showIt();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        cancelButton = new JButton();
        cancelButton.setText("Button");
        contentPane.add(cancelButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
