package com.spotifyxp.dialogs;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.spotifyxp.Initiator;
import com.spotifyxp.PublicValues;
import com.spotifyxp.configuration.ConfigValues;
import com.spotifyxp.panels.SplashPanel;
import com.spotifyxp.swingextension.CustomLengthPasswordField;
import com.spotifyxp.swingextension.CustomLengthTextField;
import com.spotifyxp.utils.AsyncActionListener;
import com.spotifyxp.utils.StartupTime;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

//ToDo: Check if this is the first start of SpotifyXP and when not support translation

public class LoginDialog extends JDialog {
    public JPanel contentPane;
    public JButton spotifyokbutton;
    public JButton spotifycancelbutton;
    public JButton facebook;
    public JLabel spotifylabelusername;
    public JLabel spotifylabelpassword;
    public CustomLengthTextField spotifyusernamefield;
    public CustomLengthPasswordField usernamepasswordfield;

    public LoginDialog() {

        $$$setupUI$$$();
        spotifyusernamefield.setColumns(10);

        usernamepasswordfield.setColumns(10);

        facebook.setText("Facebook");
        facebook.setEnabled(false);
        facebook.setToolTipText("Facebook auth not supported"); //https://github.com/SpotifyXP/SpotifyXP/issues/15
        facebook.addActionListener(new AsyncActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PublicValues.config.write(ConfigValues.facebook.name, true);
                SplashPanel.frame.setAlwaysOnTop(false);
                PublicValues.facebookcanceldialog = new CancelDialog();
                PublicValues.facebookcanceldialog.showIt();
                dispose();
            }
        }));

        spotifyokbutton.setText("Ok"); //ToDo: Translate
        spotifyokbutton.addActionListener(new AsyncActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PublicValues.config.write(ConfigValues.username.name, spotifyusernamefield.getText());
                PublicValues.config.write(ConfigValues.password.name, new String(usernamepasswordfield.getPassword()));
                PublicValues.config.write(ConfigValues.facebook.name, false);
                dispose();
            }
        }));

        spotifycancelbutton.setText("Cancel"); //ToDo: Translate
        spotifycancelbutton.addActionListener(new AsyncActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        }));

        spotifylabelusername.setText("E-Mail"); //ToDo: Translate

        spotifylabelpassword.setText("Password"); //ToDo: Translate
    }

    public void openWithInvalidAuth() {
        setContentPane(contentPane);
        setModal(true);
        setPreferredSize(new Dimension(350, 356));
        setResizable(false);
        getRootPane().setDefaultButton(spotifyokbutton);
        setTitle("Invalid Login! Try again"); //ToDo: Translate
        getRootPane().putClientProperty("JRootPane.titleBarForeground", Color.red);
        Initiator.past = true;
        SplashPanel.frame.setAlwaysOnTop(false);
        pack();
        setVisible(true);
        Initiator.past = false;
        Initiator.startupTime = new StartupTime();
        SplashPanel.frame.setAlwaysOnTop(true);
    }

    public void open() {
        setContentPane(contentPane);
        setModal(true);
        setPreferredSize(new Dimension(350, 356));
        setResizable(false);
        getRootPane().setDefaultButton(spotifyokbutton);
        setTitle("Enter Spotify Credentials"); //ToDo: Translate
        Initiator.past = true;
        SplashPanel.frame.setAlwaysOnTop(false);
        pack();
        setVisible(true);
        Initiator.past = false;
        Initiator.startupTime = new StartupTime();
        SplashPanel.frame.setAlwaysOnTop(true);
    }

    public static void main(String[] args) {
        LoginDialog dialog = new LoginDialog();
        dialog.open();
    }

    private void createUIComponents() {
        spotifyusernamefield = new CustomLengthTextField(254); //https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address
        usernamepasswordfield = new CustomLengthPasswordField(500); //https://community.spotify.com/t5/Accounts/max-password-lenght/td-p/5533953
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(9, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.setEnabled(false);
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        spotifylabelusername = new JLabel();
        spotifylabelusername.setText("Label");
        contentPane.add(spotifylabelusername, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPane.add(spacer2, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        spotifylabelpassword = new JLabel();
        spotifylabelpassword.setText("Label");
        contentPane.add(spotifylabelpassword, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        contentPane.add(spacer3, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        spotifyokbutton = new JButton();
        spotifyokbutton.setText("Button");
        panel1.add(spotifyokbutton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(139, 31), null, null, 0, false));
        spotifycancelbutton = new JButton();
        spotifycancelbutton.setText("Button");
        panel1.add(spotifycancelbutton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(139, 31), null, null, 0, false));
        facebook = new JButton();
        facebook.setText("Button");
        contentPane.add(facebook, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(314, 20), null, null, 0, false));
        contentPane.add(spotifyusernamefield, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(314, 39), null, null, 0, false));
        contentPane.add(usernamepasswordfield, new GridConstraints(5, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(314, 39), null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
